# Bun 이미지를 사용 (최신 안정 버전)
FROM oven/bun:1.1.29 AS builder

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 설치
COPY bun.lockb package.json ./
RUN bun install --frozen-lockfile

# 프로젝트 복사 및 빌드
COPY . .
RUN bun run build

# 런타임 이미지
FROM oven/bun:1.1.29 AS runner

# 작업 디렉토리 설정
WORKDIR /app

# 빌드된 파일 복사
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY package.json .

# 포트 노출 및 서버 실행
EXPOSE 3000
CMD ["bun", "run", "start"]