import { DevEnvIndicator } from '@/lib/client/components/DevEnvIndicator'
import { QueryProvider } from '@/lib/client/providers/QueryProvider'
import { SessionProvider } from '@/lib/client/providers/SessionProvider'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import type { Metadata } from 'next'
import Script from 'next/script'
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="dark">
            <body className={`antialiased`}>
                <Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" defer />

                <SessionProvider>
                    <QueryProvider>
                        {children}
                        <ReactQueryDevtools />
                        <DevEnvIndicator />
                        <Analytics />
                        <SpeedInsights />
                    </QueryProvider>
                </SessionProvider>
            </body>
        </html>
    )
}
