name: Playwright Tests

on:
    pull_request:
        branches:
            - main

jobs:
    run-e2es:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install && npx playwright install --with-deps
            - name: Build the application
              run: npm run build
            - name: Start local server
              run: |
                  nohup npm run start &   # 서버를 백그라운드에서 실행
                  npx wait-on http://localhost:3000  # 서버가 준비될 때까지 대기
            - name: Run tests
              run: npx playwright test
              env:
                  BASE_URL: 'http://localhost:3000'
