name: Playwright Tests

on:
    pull_request:
        branches:
            - main

jobs:
    run-e2es:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Create .env file
              run: echo "${{ secrets.TEST_ENV_FILE }}" > .env
            - name: Install dependencies
              run: npm install && npx playwright install --with-deps
            - name: Build the application
              run: npm run build
            - name: Start server and run tests
              run: npx start-server-and-test 'npm run start' http://localhost:3000 'npx playwright test'
              env:
                  BASE_URL: 'http://localhost:3000'
