name: Vitest Unit Tests

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Create .env file
              run: echo "${{ secrets.TEST_ENV_FILE }}" > .env

            - name: Install dependencies
              run: bun install

            - name: Run unit tests
              run: bun test:unit
